plugins:
  - jekyll-paginate

title: Salander Keeps Learning !!!
description: Forgive my poor English ~
paginate: 10
paginate_path: /page/:num/
permalink: /:title/

defaults:
  - scope:
        path: ""
    values:
        author: Salander
